/**
 * @type {import("../../typings.d").Command}
 */
module.exports = async (client, interaction, args) => {
  const user = interaction.options.getUser("user");

  if (!user)
    return client.errUsage(
      { usage: "hug [mencionar usuario]", type: "editreply" },
      interaction,
    );

  var kills = [
    ` después de un largo día, se tira en el sofá con ${user} y pone The Big Bang Theory. Tras un chiste de Sheldon Cooper, ${user} se ríe tanto que muere.`,
    `¡${interaction.user} le hizo Alt+F4 a ${user}.exe!`,
    `${interaction.user} intentó tocar la flauta y le explotó la cabeza a ${user}.`,
    `${interaction.user} se reventó los tímpanos escuchando música demasiado fuerte.`,
    `${interaction.user} reta a ${user} a una pelea a muerte. Gana ${user}.`,
    `${interaction.user} le parte la cabeza a ${user} con un teclado.`,
    `${interaction.user} aplasta a ${user} con un refrigerador.`,
    `${interaction.user} decapita a ${user} con una espada.`,
    `${interaction.user} le jala las orejas a ${user} tan fuerte que se las arranca.`,
    `${interaction.user} ahoga a ${user} en un barril de cerveza.`,
    `${interaction.user} ahoga a ${user} en una tina de chocolate caliente. *¿Qué tal tu última bebida?*`,
    `${interaction.user} destripa a ${user} con un cuchillo de mantequilla oxidado. ¡Auch!`,
    `${interaction.user} le da a ${user} galletas Oreo rellenas de pasta de dientes, y resulta que era alérgico al flúor. GGWP.`,
    `${interaction.user} se enamoró de ${user} y luego le rompió el corazón, literalmente.`,
    `${interaction.user} dispara un pavo congelado supersónico a ${user} y lo mata al instante.`,
    `${interaction.user} olvidó dejar abierta la ventana del coche y ${user} muere de calor`,
    `${interaction.user} olvidó proteger el jardín de ${user} contra zombis... Parece que los zombis se dieron un festín anoche.`,
    `${interaction.user} pone a ${user} a ver anime con él. ${user} no pudo soportarlo.`,
    `${interaction.user} agarra a ${user}, lo mete en una máquina de congelado con jugo y pone la temperatura a 100 Kelvin, creando paletas humanas.`,
    `¡${interaction.user} me contrató para matarte, pero no quiero! ${user}`,
    `${interaction.user} abraza a ${user} demasiado fuerte..`,
    `${interaction.user} hace puré a ${user} al estilo Hulk.`,
    `${interaction.user} mató a ${user} arrancándole la piel de la cara y haciéndose una máscara con ella.`,
    `${interaction.user} mata a ${user} tras horas de tortura.`,
    `${interaction.user} mata a ${user} con un candelabro en el estudio`,
    `${interaction.user} mata a ${user} a base de amabilidad`,
    `${interaction.user} mata a ${user} con su propio pie.`,
    `${interaction.user} asesina a ${user} con un hacha.`,
    `${interaction.user} pulsó suprimir. Eliminó a ${user}`,
    `${interaction.user} empuja a ${user} al frío vacío del espacio.`,
    `${interaction.user} atropella a ${user} con un PT Cruiser.`,
    `${interaction.user} le dispara a ${user} en la cabeza.`,
    `${interaction.user} dispara un láser arcoíris en la boca de ${user}, haciendo que su cabeza explote en arcoíris y ${user} renace como unicornio. :unicorn:`,
    `¡${interaction.user} le disparó a ${user} con la Base Starkiller!`,
    `${interaction.user} le echa lejía a la limonada de ${user}.`,
    `${interaction.user} estrangula a ${user}.`,
    `${interaction.user} amarra a ${user} a un misil intercontinental y lo manda con él a Corea del Norte.`,
    `${interaction.user} lanza a ${user} la maldición asesina... *¡Avada Kedavra!*`,
    `${interaction.user} le arranca los labios a ${user} después de un beso.`,
    `${interaction.user} es tan grueso que le aplasta las costillas a ${user}`,
    `${interaction.user} intenta darle a un granero enorme, falla y le da a ${user}.`,
    `${interaction.user} pone Escalofríos (película de 2015) en la tele. ${user}, que es un miedoso, muere de un infarto.`,
    `${interaction.user} tenía tanto swag que ${user} murió por ello. #Swag`,
    `${interaction.user}, ¿seguro que quieres matar a ${user}? A mí me parece buena gente.`,
    `${user} hizo clic sin querer en un anuncio que decía \`¡Los médicos nos odian: descubre el mejor truco para morir hoy!\``,
    `${user} tropezó y murió al levantarse para escribir su nota de despedida.`,
    `${user} comió un trozo de mantequilla exótica. Estaba tan buena que lo mató.`,
    `${user} se comió una manzana que resultó ser de cera. Alguien murió intoxicado con cera ese mismo día.`,
    `${user} tomó demasiados laxantes y se ahogó en su propia caca. Qué asco.`,
    `${user} se desangra intentando salir en \`Los momentos más tontos de los paletos\`.`,
    `${user} se compró un fidget spinner y se ahogó en su propia vergüenza.`,
    `${user} no puede morir porque es un fantasma.`,
    `${user} se asfixia en un bote de basura.`,
    `${user} se atraganta con un hueso de pollo.`,
    `${user} se atraganta con cereales y muere. Qué idiota...`,
    `${user} sube el volumen del equipo de música y se da cuenta de que estaba al máximo y sonaba Baby de Justin Bieber...`,
    `${user} se queda ciego por un accidente, corre a pedir ayuda, se mete en las vías del tren y lo arrolla un tren.`,
    `${user} pensó que era buena idea pelear con un tigre oliendo a carne. No terminó bien.`,
    `${user} no hizo un meme lo bastante bueno y lo apedrearon.`,
    `${user} murió tras hacer algo 50 veces seguidas sin descanso.`,
    `${user} murió tras jugar 90 horas seguidas sin moverse ni comer.`,
    `${user} murió tras jugar con un fidget spinner de cuchillas.`,
    `${user} murió al darse cuenta de lo mala que era su ortografía`,
    `${user} murió intentando hacer mejores memes que Dank Memer.`,
    `${user} tuvo una muerte honorable. Muerte por snu snu.`,
    `${user} murió porque RemindMeBot olvidó recordarle que respirara`,
    `${user} murió porque empezó a jugar con un fidget spinner, se dio cuenta de que estaba en 2016, Obama empezó a cortar su césped, saltó por la ventana y la cortadora de césped de Obama lo hizo pedazos`,
    `${user} murió porque ${interaction.user} es demasiado tonto`,
    `${user} murió por comer DEMASIADOS hot dogs preparándose para su cita del viernes por la noche.`,
    `${user} murió comiendo sushi de pescado crudo caducado e infectado con el arroz más sucio del mundo. La salsa de soya era pis de gato.`,
    `${user} murió por comer demasiada sal`,
    `${user} murió de una patada rápida al cerebro.`,
    `${user} murió por una cantidad trágica de mala suerte`,
    `${user} murió haciendo el reto del cubo de hielo.`,
    `${user} murió por beber demasiada agua. ¡Vaya, parece que SÍ es posible!`,
    `${user} murió por comer espinas de cactus.`,
    `${user} murió por comer demasiada basura.`,
    `${user} murió por comer demasiado pan :/`,
    `${user} murió de ébola.`,
    `${user} murió por falta de memes :/`,
    `${user} murió por no comer suficiente basura.`,
    `${user} murió por no descansar lo suficiente. (Hay que tener un equilibrio, chicos)`,
    `${user} murió por hacer reposts en el barrio equivocado`,
    `${user} murió tras pasar 36 horas seguidas en el baño.`,
    `${user} murió por tragar piedras demasiado rápido`,
    `${user} murió por demasiadas quemaduras de sol.`,
    `${user} murió por no descansar nunca. (Hay que tener un equilibrio, chicos)`,
    `${user} murió de exceso de todo`,
    `${user} murió probando una bomba de hidrógeno. No quedó nada que enterrar.`,
    `${user} murió escuchando 'It's every day bro'`,
    `${user} murió jugando a la rayuela sobre minas *aparentemente* desactivadas.`,
    `${user} murió intentando encontrar la ciudad de Inglaterra`,
    `${user} murió. OOF`,
    `${user} muere tras tragarse un palillo.`,
    `${user} muere a manos de ${interaction.user}.`,
    `${user} muere por usar una horquilla para rizarse las pestañas`,
    `${user} muere porque estaba demasiado enojado.`,
    `${user} muere por decir groserías en un servidor cristiano de Minecraft`,
    `${user} muere por falta de amigos.`,
    `${user} muere por mala suerte.`,
    `${user} muere por hacer el dab demasiado fuerte.`,
    `${user} muere por hacer el dab demasiado fuerte`,
    `${user} muere por faltarle el respeto a los demás.`,
    `${user} muere por ser simplemente un tipo malo y antipático.`,
    `${user} muere por publicar memes de normie.`,
    `${user} muere por su profundo odio a la arena. Es áspera, tosca e irritante, y se mete en todas partes`,
    `${user} muere por ver Emoji: la película y disfrutarla.`,
    `${user} muere en un terrible accidente, y fue obra de ${interaction.user}.`,
    `${user} muere al norte del Muro y se convierte en caminante blanco`,
    `${user} muere de sida.`,
    `${user} muere de disentería.`,
    `${user} muere por causas naturales.`,
    `${user} muere de hambre.`,
    `${user} muere en el corredor de la muerte por inyección letal tras asesinar a ${interaction.user} y a su familia.`,
    `${user} muere, pero no dejes que eso te distraiga del hecho de que en 1998, The Undertaker lanzó a Mankind desde lo alto de Hell In A Cell y cayó 5 metros sobre la mesa de comentaristas`,
    `${user} muere.`,
    `Tras un forcejeo, ${user} mata a ${interaction.user}`,
    `${user} desapareció del universo.`,
    `${user} se tomó un refresco tóxico antes de que lo retiraran del mercado.`,
    `${user} se le cayó un Nokia en la cara y se partió el cráneo.`,
    `${user} se ahogó en sus propias lágrimas.`,
    `${user} come demasiada copypasta y explota`,
    `${user} se cayó por un acantilado jugando Pokémon Go. Bien hecho por no despegar la nariz de ese diminuto teléfono. :iphone:`,
    `${user} se cayó a un pozo lleno de gente enojada.`,
    `${user} es atropellado por un coche.`,
    `${user} es apuñalado por ${interaction.user}`,
    `${user} es alcanzado por un rayo.`,
    `¡${user} va por la ruta genocida y Sans lo destroza por completo!`,
    `${user} se metió en una pelea a cuchillo con el papa. Uno de los dos está ahora en el infierno.`,
    `${user} fue pisado por un elefante.`,
    `${user} murió por comer demasiada basura.`,
    `${user} sufre un derrame tras una existencia triste y miserable. Luego se lo comen sus muchos gatos.`,
    `¡${user} fue declarado culpable, llegó la hora de su ejecución!`,
    `${user} comió comida china en mal estado y pagó el precio más alto.`,
    `${user} es abducido por extraterrestres, y el gobierno lo mata para encubrirlo.`,
    `${user} muere a manos de ${interaction.user}.`,
    `A ${user} le inyectan jarabe de chocolate, que lo convierte en una persona de chocolate. Mientras trabaja medio tiempo en la guardería, se lo comen los bebés hambrientos. :chocolate_bar:`,
    `${user} es asesinado por un conejo con muy mala leche`,
    `${user} es asesinado por su propia estupidez.`,
    `${user} muere en un robo que salió mal.`,
    `${user} no puede morir. Ah, espera, no, ${interaction.user} lo mata de todas formas.`,
    `${user} es tan tonto que se atragantó con oxígeno.`,
    `Freddy mete a ${user} dentro de un traje durante su turno de guardia nocturno. ¡Otra vez esos animatrónicos no!`,
    `${user} es absorbido por Minecraft. ${user}, un novato en el llamado Minecraft de la vida real, se enfrenta a la pantalla de Game Over.`,
    `${user} se murió tras ver los memes de normie que publica ${interaction.user}.`,
    `${user} se murió al darse cuenta de lo tonto que es ${interaction.user}.`,
    `${user} sigue vivo, a pesar del intento de asesinato de ${interaction.user}.`,
    `${user} pierde las ganas de vivir`,
    `${user} pulsa un botón al azar y se teletransporta a 100 m de altura, lo que le permite caer hacia su muerte inevitable. Moraleja: no vayas por ahí pulsando botones al azar.`,
    `${user} lee memes hasta morir.`,
    `${user} se arrancó el corazón..`,
    `${user} se arrancó el corazón para demostrarle su amor a ${interaction.user}.`,
    `${user} grita aterrorizado al invocar sin querer a Cthulhu mientras decía palabras en latín al azar. Cthulhu agarra a ${user} de la pierna derecha y se lo lleva a su dimensión gritando: \`¡Cariño, la cena está lista!\``,
    `${user} se resbaló en el baño y se ahogó con la cortina de la ducha.`,
    `${user} se resbala con una cáscara de plátano y cae por las escaleras.`,
    `${user} gira un fidget spinner y, cuando se detiene, muere...`,
    `${user} pisa una parrilla George Foreman y muere de pie de waffle.`,
    `${user} recibe una flecha en la rodilla. Y en todas partes.`,
    `${user} le contestó a los moderadores y el martillo del baneo lo destruyó.`,
    `${user} se inclina demasiado el sombrero y cae a las vías de un metro que se acerca.`,
    `${user} intentó hacer manualidades, pero se cortó sin querer con las tijeras.:scissors:`,
    `${user} intentó hacerse famoso en YouTube transmitiendo en vivo algo estúpido: saltar en paracaídas encadenado a un refrigerador.`,
    `${user} intentó ganarle una carrera a un tren. Ganó el tren.`,
    `${user} intentó elegir el Santo Grial. Eligió... mal.`,
    `${user} intentó jugar en medio de la calle...`,
    `${user} se tropieza con sus propios cordones y muere.`,
    `${user} se opuso públicamente a los Clinton y de repente desapareció.`,
    `${user} vivía en Alderaan antes de que Darth Vader destruyera el planeta...`,
    `${user} fue acusado de robar la corona de Neptuno...`,
    `${user} estaba cargando su Samsung Galaxy Note 7...`,
    `${user} fue devorado vivo por hormigas`,
    `${user} tuvo la oportunidad de sintetizar el elemento 119 (ununennio) y ponerle su nombre, pero la fastidió. D.E.P.`,
    `${user} fue asesinado por ${interaction.user} con toallitas húmedas.`,
    `${user} fue asesinado por ${interaction.user} y todos lo saben, pero no hay pruebas.`,
    `${user} fue vaciado por ${interaction.user} y ahora sus entrañas son Ennard.`,
    `${user} fue teletransportado a la línea temporal en la que Jurassic World era real y se lo comió vivo el Indominus Rex.`,
    `${user} fue arrojado a la trituradora de un camión de basura por ${interaction.user}.`,
    `${user} caminaba tranquilamente cuando, de reojo, vio a alguien hacer un bottle flip y un dab, y le dio un derrame.`,
    `${user} vio Emoji: la película y murió de vergüenza ajena.`,
    `${user} se fue de paseo en un globo de plomo.`,
    `Después de que ${interaction.user} lo empujara al océano, a ${user} se lo come un tiburón.`,
    `Después de que un raid de niños de Roblox entrara al servidor, ${user} murió de cáncer.`,
    `Sida, ${user} murió de sida.`,
    `Invocando los poderes divinos, ${interaction.user} castiga a ${user} y sus costumbres paganas`,
    `En un giro inesperado, **no** mato a ${user}.`,
    `no, tú`,
    `Nuestro señor y salvador Gaben fulmina a ${user} con un rayo.`,
    `Lo siento, ${interaction.user}, no me gusta matar gente.`,
    `La bala no le dio a Harambe y le dio a ${user}. ¡Bien por Harambe!`,
    `Mientras le hacía una colonoscopia a un elefante, a ${user} se le quedó atascada la cabeza en el recto del elefante y se asfixió.`,
  ];

  client.embed(
    {
      title: `🔫・Matar`,
      desc: `${kills[Math.floor(Math.random() * kills.length)]}`,
      type: "editreply",
    },
    interaction,
  );
};
