/**
 * @type {import("../../typings.d").Command}
 */
module.exports = async (client, interaction, args) => {
  const user = interaction.options.getUser("user");

  var roasts = [
    "*Te mete al horno.*",
    "Eres tan tonto.",
    "Perdón, no te escucho por lo molesto que eres.",
    "Tengo cosas mejores que hacer.",
    "Eres tan tonto como Cleverbot.",
    "Tu coeficiente intelectual es más bajo que la fosa de las Marianas.",
    "Eres tan molesto que hasta las moscas huyen de tu olor.",
    "Vete, por favor.",
    "Te pondría mala cara, pero ya tienes una.",
    "Parece que tu cara se prendió fuego y alguien intentó apagarlo con un martillo.",
    "Tu árbol genealógico debe de ser un cactus, porque todos en él son unos pinchos.",
    "Algún día llegarás lejos, y espero que te quedes allí.",
    "Llamaron del zoológico. Se preguntan cómo saliste de tu jaula.",
    "Esperaba una batalla de ingenio, pero parece que vienes desarmado.",
    "Eres la prueba de que la evolución puede ir hacia atrás.",
    "El cerebro no lo es todo; en tu caso, no es nada.",
    "Perdón, no te entendí, no hablo idiota.",
    "¿Por qué tú puedes ser idiota y yo no puedo señalarlo?",
    "Todos venimos de los monos, pero tú no te alejaste lo suficiente.",
    "Hasta los monos pueden ir al espacio, así que está claro que te falta potencial.",
    "Más vale cerebro que músculo, y tú no tienes ninguno de los dos.",
    "Pareces un mono y hueles como uno.",
    "Hasta entre idiotas te quedas corto.",
    "Fallas incluso cuando no haces absolutamente nada.",
    "Si hubiera un premio al 'menos probable de triunfar', te llevarías el primer lugar.",
    "Estoy rodeado de idiotas... Ah, no, espera, solo eres tú.",
    "Me quiero ir a casa. Bueno, en realidad solo quiero alejarme del olor horrible que traes.",
    "Cada vez que me tocas tengo que ir a casa y lavar toda mi ropa nueve veces para que vuelva a oler normal.",
    "Si tuviera un dólar por cada cerebro que no tienes, tendría un dólar.",
    "Te ayudaría a triunfar, pero eres incapaz.",
    "Tu línea del cabello parece una gráfica: las fuerzas positivas y negativas se atraen, pero la máquina de cortar y tu pelo se repelen.",
    "¡Me sé un buen chiste! ¡Tú!",
    "Tu cerebro tiene dos partes, 'izquierda' y 'derecha'. En la izquierda no hay nada derecho. En la derecha no queda nada.",
    "¿Tu trasero no está celoso de la cantidad de basura que acaba de salir de tu boca?",
    "No entro en combates mentales con gente desarmada.",
    "Dos errores no hacen un acierto; mira a tus padres como ejemplo.",
    "Tu acta de nacimiento es una carta de disculpa de la fábrica de condones.",
    "Suenas razonable. ¡Debe de ser hora de subirme la medicación!",
    "Debiste nacer en una autopista, porque ahí es donde ocurren la mayoría de los accidentes.",
    "Eres tan feo que, cuando tu mamá te dejó en la escuela, le pusieron una multa por tirar basura.",
    "Si la risa es la mejor medicina, tu cara debe de estar curando al mundo.",
    "Me gustaría ver las cosas desde tu punto de vista, pero no consigo meter la cabeza tan adentro de mi trasero.",
    "La única forma de que ligues es que te metas en el trasero de una gallina y esperes.",
    "¡Envidio a toda la gente que no te conoce!",
    "Si tuviera una cara como la tuya, demandaría a mis padres.",
    "Tu cara tiene un solo problema: que la puedo ver.",
    "¿No te encanta la naturaleza, a pesar de lo que te hizo?",
    "¿Qué idioma hablas? Porque suena a pura tontería.",
    "La estupidez no es un delito, así que puedes irte.",
    "¿Así que se te cruzó un pensamiento por la mente? Debió de ser un viaje largo y solitario.",
    "Tu coeficiente intelectual está a temperatura ambiente... si la habitación está en la Antártida.",
    "Si de verdad quieres saber de errores, pregúntale a tus padres.",
    "Te preguntaría cuántos años tienes, pero sé que no sabes contar tan alto.",
    "¿Quieres saber de dónde saco todos estos insultos? Uso algo llamado inteligencia.",
    "Te iba a poner mala cara, pero ya tienes una.",
    "No sé cuál es tu problema, pero apuesto a que es difícil de pronunciar.",
    "El cerebro no lo es todo. En tu caso no es nada.",
    "Como observador externo, ¿qué opinas de la raza humana?",
    "Pareces la foto del 'antes'.",
    "¿Eh, qué? Perdón. Estaba intentando imaginarte con personalidad.",
    "Eres la razón por la que el acervo genético necesita un salvavidas.",
    "Siempre sabemos cuándo mientes. Mueves los labios.",
    "Me encanta ir de compras, pero tus tonterías no te las compro.",
    "El infierno está empapelado con todas las selfies que borraste.",
    "Eres la prueba viviente de que el estiércol puede echar patas y caminar.",
    "¿Te das cuenta de que el maquillaje no va a arreglar tu estupidez?",
    "Llamarte idiota sería un insulto para todos los tontos.",
    "Tienes la cara perfecta para la radio.",
    "Aww, qué tierno cuando intentas hablar de cosas que no entiendes.",
    "Si quisiera oír a un imbécil, me tiraría un pedo.",
    "¿Cuál es la diferencia entre tú y un huevo? ¡Que a los huevos alguien los pone!",
    "Pareces una roca hecha arena, enrollada y fumada con un inhalador para el asma.",
    "Tus consejos son tan útiles como un refugio antiaéreo de papel maché.",
    "¿No es triste que tu canción favorita bien podría tener un compás de 0/0?",
    "Eres tan gordo que haces que la galaxia parezca de escala molecular.",
  ];

  client.embed(
    {
      title: `😓・Humillación`,
      desc: `${user}, ${roasts[Math.floor(Math.random() * roasts.length)]}`,
      type: "editreply",
    },
    interaction,
  );
};
